import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Health Servey App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>health servey app</header>
      <main className={styles.main}>
        <section>content</section>
      </main>

      <footer className={styles.footer}>
        <div>Copyright © jeongdain 2022</div>
      </footer>
    </div>
  );
}

export default Home
